const { chromium } = require(process.env.TOK_PLAYWRIGHT || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
 const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
 try {
  const page = await browser.newPage({viewport:{width:1600,height:1050}});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message)); page.on('dialog', d=>d.accept());
  await page.goto('file://' + path.resolve('packages/tok-ui/dist/TypesetOK.html'));
  await page.click('[data-action="templates"]');
  assert.equal(await page.locator('.template-card').count(),8);
  await page.screenshot({path:'/tmp/typesetok-templates.png'});
  await page.getByRole('button',{name:'עבודה סיכום פגישה',exact:false}).click();
  assert.equal(await page.locator('#title').inputValue(),'סיכום פגישה');
  assert.equal(await page.locator('#editor h2').count(),4);
  await page.fill('#library-query','משימות להמשך');
  assert.equal(await page.locator('.doc-card').count(),1);
  await page.fill('#library-query','אין-כזה-מסמך');
  assert.equal(await page.locator('.doc-card').count(),0);
  await page.fill('#library-query','');
  await page.selectOption('#library-sort','title');
  assert.equal(await page.locator('.doc-card').count(),2);
  await page.click('[data-action="snapshot"]');
  await page.click('[data-inspect="notes"]');
  await page.fill('#notes','הערת גיבוי');
  const downloading=page.waitForEvent('download'); await page.click('[data-action="backup"]');
  const file=await downloading; const raw=fs.readFileSync(await file.path());
  const backup=JSON.parse(raw); assert.equal(backup.documents.length,2);
  assert.ok(backup.documents.some(d=>d.doc.notes==='הערת גיבוי'));
  assert.ok(backup.documents.some(d=>d.snapshots.length===1));
  await page.setInputFiles('#library-file',{name:'backup.toklibrary',mimeType:'application/json',buffer:raw});
  await page.waitForFunction(()=>document.querySelectorAll('.doc-card').length===4);
  await page.reload(); assert.equal(await page.locator('.doc-card').count(),4);
  const before = await page.evaluate(()=>localStorage.getItem('typesetok.studio.v1'));
  await page.setInputFiles('#library-file',{name:'bad.toklibrary',mimeType:'application/json',buffer:Buffer.from('{"format":"toklibrary","version":1,"documents":[{}]}')});
  await page.waitForFunction(()=>!document.querySelector('#toast').hidden);
  assert.equal(await page.locator('.doc-card').count(),4);
  assert.equal(await page.evaluate(()=>localStorage.getItem('typesetok.studio.v1')),before);
  const hostile=JSON.parse(raw); hostile.documents=hostile.documents.slice(0,1);
  hostile.documents[0].doc.html='<p onclick="window.pwned=1">בדיקה</p><script>window.pwned=1</script>';
  await page.setInputFiles('#library-file',{name:'hostile.toklibrary',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(hostile))});
  await page.waitForFunction(()=>document.querySelectorAll('.doc-card').length===5);
  await page.locator('.doc-card').last().click();
  assert.equal(await page.locator('#editor script,#editor [onclick]').count(),0);
  assert.equal(await page.evaluate(()=>window.pwned),undefined);
  await page.click('[data-tab="review"]'); await page.click('[data-action="readingStats"]');
  assert.ok((await page.locator('#modal-body').innerText()).includes('זמן קריאה משוער'));
  await page.click('[data-action="closeModal"]');
  await page.screenshot({path:'/tmp/typesetok-workspace.png'});
  assert.deepEqual(errors,[]);
  console.log('Library checks passed: templates, content search, empty search, sorting, backup including notes/snapshots, additive restore, persistence, invalid input isolation, HTML sanitization, reading statistics.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
