import {MAX_TEXT,defaults,sample,validateDraft,stats,countMatches,transform,History} from './model.js';
const $=id=>document.getElementById(id), editor=$('editor'), key='typesetok.draft.v1';
let draft={format:'tokdraft',version:1,title:'הסיפור הבא שלי',text:sample,settings:{...defaults}}, history, zoom=.75, timer, saveTimer, toastTimer, dirty=false, composing=false, lastInput=0, rendered=0, previewLimited=false;
let printStyle=document.createElement('style');document.head.append(printStyle);
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
try{const saved=localStorage.getItem(key);if(saved)draft=validateDraft(JSON.parse(saved));document.body.classList.toggle('dark',localStorage.getItem('typesetok.theme')==='dark');}catch{setTimeout(()=>toast('לא ניתן לשחזר טיוטה מקומית. אפשר לפתוח קובץ שמור.'),100);}
function readText(){draft.text=editor.value;draft.title=$('title').value||'מסמך חדש';}
function persist(){clearTimeout(saveTimer);readText();try{localStorage.setItem(key,JSON.stringify(draft));$('save-state').textContent='טיוטה נשמרה במכשיר · '+new Date().toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'});}catch{$('save-state').textContent='שמירה מקומית נכשלה — שמרי קובץ';}}
function changed(){dirty=true;$('save-state').textContent='שומר טיוטה…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,700);schedule();}
function sync(){editor.value=draft.text;$('title').value=draft.title;for(const [id,value]of Object.entries(draft.settings)){if(typeof value==='boolean')$(id).checked=value;else $(id).value=String(value);}editor.dir=draft.settings.direction;history=new History(draft.text);render();}
function schedule(){clearTimeout(timer);timer=setTimeout(render,180);}
function updateHistory(){history.push(editor.value);$('undo').disabled=history.index===0;$('redo').disabled=history.index===history.items.length-1;}
function replaceSelection(text,all=false){const start=all?0:editor.selectionStart,end=all?editor.value.length:editor.selectionEnd;if(editor.value.length-(end-start)+text.length>MAX_TEXT){toast('המגבלה היא 500,000 תווים למסמך');return;}history.push(editor.value);editor.setRangeText(text,start,end,'end');history.push(editor.value);lastInput=0;changed();editor.focus();}
function dimensions(){const [w,h]={A4:[210,297],A5:[148,210],Letter:[216,279]}[draft.settings.paper];return draft.settings.orientation==='landscape'?[h,w]:[w,h];}
function pageNode(text,index,maxBlocks=Infinity){const s=draft.settings,[w,h]=dimensions(),page=document.createElement('article');page.className='page'+(s.guides?' guides':'');page.dir=s.direction;Object.assign(page.style,{width:w+'mm',minHeight:h+'mm',padding:s.margin+'mm',fontFamily:s.font,fontSize:s.size+'pt',lineHeight:String(s.leading),textAlign:s.align});page.style.setProperty('--spacing',s.spacing+'px');page.style.setProperty('--indent',s.indent?'1.5em':'0');page.style.setProperty('--margin',s.margin+'mm');
 for(const block of text.split(/\n\s*\n/u).slice(0,maxBlocks)){if(!block.trim())continue;for(const segment of block.split(/\n(?=#{1,2} )/u)){let tag='p',content=segment;if(/^## /u.test(content)){tag='h2';content=content.slice(3);}else if(/^# /u.test(content)){tag='h1';content=content.slice(2);}const node=document.createElement(tag);node.textContent=content;page.append(node);}}
 if(s.numbers){const folio=document.createElement('div');folio.className='folio';folio.textContent=String(index+1);page.append(folio);}return page;}
function render(){readText();const values=stats(draft.text),pages=draft.text.split(/^---\s*$/m);$('stats').textContent=`${values.words.toLocaleString('he-IL')} מילים · ${values.characters.toLocaleString('he-IL')} תווים · ${pages.length} מקטעי עמוד · כ־${Math.max(1,Math.ceil(values.words/200))} דק׳ קריאה`;
 // The preview intentionally mounts at most 12 sections. Export uses all sections.
 previewLimited=pages.length>12||draft.text.length>30000||pages.some(text=>text.split(/\n\s*\n/u).length>300);let budget=30000;const fragment=document.createDocumentFragment();pages.slice(0,12).forEach((text,i)=>{if(budget<=0)return;const clipped=text.slice(0,budget);budget-=clipped.length;fragment.append(pageNode(clipped,i,300));});$('preview').replaceChildren(fragment);rendered=Math.min(12,pages.length);if(previewLimited){const notice=document.createElement('p');notice.textContent='תצוגה מקוצרת למסמך ארוך כדי לשמור על ביצועים. ייצוא HTML כולל את כל הטקסט.';$('preview').append(notice);}
 $('preview').style.zoom=String(zoom);$('zoom-label').textContent=Math.round(zoom*100)+'%';editor.dir=draft.settings.direction;
 const outline=document.createDocumentFragment();let offset=0;for(const line of draft.text.split('\n')){if(/^#{1,2} /u.test(line)&&outline.childNodes.length<100){const button=document.createElement('button'),position=offset;button.textContent=line.replace(/^#+ /,'');button.addEventListener('click',()=>{editor.focus();editor.setSelectionRange(position,position+line.length);});outline.append(button);}offset+=line.length+1;}$('outline').replaceChildren(outline);$('matches').textContent=$('query').value?countMatches(draft.text,$('query').value)+' התאמות':'';$('undo').disabled=history.index===0;$('redo').disabled=history.index===history.items.length-1;printStyle.textContent=`@page { size: ${draft.settings.paper} ${draft.settings.orientation}; margin: ${draft.settings.margin}mm; }`;}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function filename(ext){return (draft.title.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,100)||'document')+ext;}
function exportHtml(){readText();const doc=document.implementation.createHTMLDocument(draft.title);doc.documentElement.lang='he';doc.documentElement.dir=draft.settings.direction;const meta=doc.createElement('meta');meta.setAttribute('charset','utf-8');doc.head.prepend(meta);const policy=doc.createElement('meta');policy.httpEquiv='Content-Security-Policy';policy.content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'";doc.head.append(policy);const style=doc.createElement('style');style.textContent=`body{margin:0;background:#eee}.page{box-sizing:border-box;background:white;margin:20px auto;overflow-wrap:anywhere;break-after:page}.page p{white-space:pre-wrap;margin:0 0 var(--spacing);text-indent:var(--indent)}.folio{text-align:center;margin-top:30px}h1,h2{break-after:avoid}.page:last-child{break-after:auto}@page{size:${draft.settings.paper} ${draft.settings.orientation};margin:${draft.settings.margin}mm}@media print{body{background:white}.page{margin:0;width:auto!important;min-height:0!important;padding:0!important}}`;doc.head.append(style);draft.text.split(/^---\s*$/m).forEach((text,i)=>doc.body.append(pageNode(text,i)));return '<!doctype html>\n'+doc.documentElement.outerHTML;}
function findNext(){const q=$('query').value;if(!q)return toast('כתבי טקסט לחיפוש');let pos=editor.value.indexOf(q,editor.selectionEnd);if(pos<0)pos=editor.value.indexOf(q);if(pos<0)return toast('לא נמצאו התאמות');editor.focus();editor.setSelectionRange(pos,pos+q.length);$('matches').textContent=countMatches(editor.value,q)+' התאמות';}
const actions={
 new(){clearTimeout(editor.historyTimer);if(dirty&&!confirm('להתחיל מסמך חדש? ודאי ששמרת עותק של המסמך הנוכחי.'))return;draft={format:'tokdraft',version:1,title:'מסמך חדש',text:'',settings:{...defaults}};sync();dirty=true;persist();editor.focus();},
 open(){$('file').click();},save(){readText();download(filename('.tokdraft'),JSON.stringify(draft,null,2),'application/json');dirty=false;persist();toast('קובץ הטיוטה הוכן להורדה');},txt(){readText();download(filename('.txt'),draft.text,'text/plain;charset=utf-8');},html(){download(filename('.html'),exportHtml(),'text/html;charset=utf-8');},
 print(){render();if(previewLimited){toast('למסמך ארוך: ייצאי HTML, פתחי אותו והדפיסי משם כדי לכלול את כל העמודים.');return;}document.body.classList.remove('focus');window.print();},
 undo(){updateHistory();editor.value=history.undo();changed();render();},redo(){editor.value=history.redo();changed();render();},search(){$('search-panel').hidden=!$('search-panel').hidden;if(!$('search-panel').hidden)$('query').focus();},find:findNext,
 replace(){const q=$('query').value;if(!q)return;if(editor.value.slice(editor.selectionStart,editor.selectionEnd)===q)replaceSelection($('replacement').value);findNext();},replaceAll(){const q=$('query').value;if(!q)return;const n=countMatches(editor.value,q);if(n===0)return toast('לא נמצאו התאמות');const replacement=$('replacement').value;if(editor.value.length+n*(replacement.length-q.length)>MAX_TEXT)return toast('התוצאה חורגת ממגבלת גודל המסמך');replaceSelection(editor.value.split(q).join(replacement),true);toast(`הוחלפו ${n} מופעים`);},
 focus(){document.body.classList.toggle('focus');},theme(){document.body.classList.toggle('dark');try{localStorage.setItem('typesetok.theme',document.body.classList.contains('dark')?'dark':'light');}catch{}},help(){$('help').showModal();},closeHelp(){$('help').close();},selectAll(){editor.focus();editor.select();},
 zoomIn(){zoom=Math.min(1.5,zoom+.1);schedule();},zoomOut(){zoom=Math.max(.3,zoom-.1);schedule();},zoomReset(){zoom=.75;schedule();},fit(){zoom=Math.max(.3,Math.min(1.5,($('preview-scroll').clientWidth-50)/(dimensions()[0]*96/25.4)));schedule();},
 heading(){replaceSelection('# '+editor.value.slice(editor.selectionStart,editor.selectionEnd));},subheading(){replaceSelection('## '+editor.value.slice(editor.selectionStart,editor.selectionEnd));},pagebreak(){replaceSelection('\n\n---\n\n');},maqaf(){replaceSelection('־');},gershayim(){replaceSelection('״');},nbsp(){replaceSelection('\u00a0');},date(){replaceSelection(new Date().toLocaleDateString('he-IL'));},
 template(){const presets={article:{size:14,leading:1.8,paper:'A4',align:'justify',indent:false},book:{size:12,leading:1.6,paper:'A5',align:'justify',indent:true},poem:{size:16,leading:2,paper:'A5',align:'center',indent:false},letter:{size:13,leading:1.7,paper:'A4',align:'right',indent:false}};readText();Object.assign(draft.settings,presets[$('template').value]);for(const[id,value]of Object.entries(draft.settings)){if(typeof value==='boolean')$(id).checked=value;else $(id).value=String(value);}changed();toast('סגנון התבנית הוחל על המסמך');}
};
for(const action of ['normalize','spaces','niqqud','marks'])actions[action]=()=>{const selected=editor.selectionStart!==editor.selectionEnd;replaceSelection(transform(selected?editor.value.slice(editor.selectionStart,editor.selectionEnd):editor.value,action),!selected);};
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button)actions[button.dataset.action]?.();});
editor.addEventListener('paste',event=>{const text=event.clipboardData?.getData('text/plain');if(text===undefined)return;event.preventDefault();replaceSelection(text);});
editor.maxLength=MAX_TEXT;editor.addEventListener('compositionstart',()=>composing=true);editor.addEventListener('compositionend',()=>{composing=false;updateHistory();changed();});editor.addEventListener('beforeinput',()=>{if(Date.now()-lastInput>600)history.push(editor.value);});editor.addEventListener('input',()=>{lastInput=Date.now();if(!composing){changed();clearTimeout(editor.historyTimer);editor.historyTimer=setTimeout(updateHistory,600);}});editor.addEventListener('select',()=>{$('selection-stats').textContent=editor.selectionEnd>editor.selectionStart?`${editor.selectionEnd-editor.selectionStart} תווים בבחירה`:'';});
$('title').addEventListener('input',changed);$('spell').addEventListener('change',()=>editor.spellcheck=$('spell').checked);$('query').addEventListener('input',()=>{$('matches').textContent=countMatches(editor.value,$('query').value)+' התאמות';});
for(const[id,value]of Object.entries(defaults))$(id).addEventListener('change',()=>{const next=typeof value==='boolean'?$(id).checked:typeof value==='number'?Number($(id).value):$(id).value;try{draft=validateDraft({...draft,settings:{...draft.settings,[id]:next}});changed();}catch{toast('ערך מחוץ לטווח');$(id).value=String(draft.settings[id]);}});
$('file').addEventListener('change',async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>4_000_000)throw Error('הקובץ גדול מדי — עד 4 MB');const raw=await file.text();const loaded=file.name.toLowerCase().endsWith('.txt')?validateDraft({format:'tokdraft',version:1,title:file.name.slice(0,-4).slice(0,120),text:raw,settings:{...defaults}}):validateDraft(JSON.parse(raw));if(dirty&&!confirm('לפתוח קובץ אחר? ודאי ששמרת עותק של המסמך הנוכחי.'))return;draft=loaded;clearTimeout(editor.historyTimer);sync();dirty=false;persist();toast('המסמך נפתח');}catch(error){toast(error.message||'לא ניתן לפתוח את הקובץ');}finally{$('file').value='';}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.body.classList.remove('focus');if(!(event.ctrlKey||event.metaKey)||event.altKey)return;const key=event.key.toLowerCase();const action={s:'save',o:'open',f:'search',z:event.shiftKey?'redo':'undo',y:'redo'}[key];if(action){if(['undo','redo'].includes(action)&&event.target!==editor)return;event.preventDefault();clearTimeout(editor.historyTimer);actions[action]();}});
window.addEventListener('beforeunload',event=>{persist();if(dirty){event.preventDefault();event.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();});sync();
